version: "3.7"
services:
  db:
    image: mysql:8.0
    environment:
      - "MYSQL_DATABASE=mta"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

